openapi: "3.0.2"
info:
  title: CoChat API Reference
  version: "1.0"
servers:
  - url: https://api.server.test/v1

tags:
  - name: user
    description: Operations about user

paths:
  /api/user/login:
    post:
      tags:
        - user
      summary: 用户登录
      description: 本接口只能在用户登录时访问，注册是/api/user/register
      operationId: userLogin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: 成功响应
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTResponse'
        '404':
          description: 用户不存在，info为"User Not Found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
        '401':
          description: 密码错误，info为"Password Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
        '405':
          description: 请求方法错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadMethodResponse'
        '500':
          description: 服务器内部错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

  /api/user/register:
    post:
      tags:
        - user
      summary: 用户注册
      description: 用户基本的注册信息，可传email/avatar，注册后自动置为登录状态
      operationId: userRegister
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - user_name
                - password
              properties:
                user_name:
                  type: string
                  description: 用户名，长度小于等于50
                  example: "Plato"
                password:
                  type: string
                  description: 用户密码（前端加密后），加密后长度小于等于50
                  example: "123456"
                user_email:
                  type: string
                  format: email
                  description: 用户邮箱，长度小于等于100
                  example: "Plato@163.com"
                avatar:
                  type: string
                  format: binary
                  description: 用户头像
                  example: "{FILE BINARY}"
      responses:
        '200':
          description: 成功响应
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTResponse'
        '409':
          description: 该用户已经存在，info为"Username conflict"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictResponse'
        '405':
          description: 请求方法错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadMethodResponse'
        '500':
          description: 服务器内部错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

  /api/user/{username}:
    delete:
      tags:
        - user
      summary: 用户注销
      description: 注销该用户，删除所有关联信息（消息、好友、群聊）
      operationId: deleteUser
      requestBody:
        content:
          application/json:
            schema:
              properties:
                token:
                  type: string
                  description: JWT令牌
                  example: "***.***.***"
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '405':
          description: 请求方法错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadMethodResponse'
        '500':
          description: 服务器内部错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
    post:
      tags:
        - user
      summary: 用户更新个人信息
      description: 更新用户名、密码、头像、邮箱等，注：旧密码需在前端验证
      operationId: deleteUser
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  description: JWT令牌
                  example: "***.***.***"
                user_name:
                  type: string
                  description: 用户名，长度小于等于50
                  example: "Plato"
                password:
                  type: string
                  description: 用户新密码（前端加密后），加密后长度小于等于50
                  example: "123456"
                user_email:
                  type: string
                  format: email
                  description: 用户邮箱，长度小于等于100
                  example: "Plato@163.com"
                avatar:
                  type: string
                  format: binary
                  description: 用户头像
                  example: "{FILE BINARY}"
      responses:
        '200':
          description: 成功响应，返回新的JWT令牌
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTResponse'
        '409':
          description: 该用户已经存在，info为"Username conflict"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictResponse'
        '405':
          description: 请求方法错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadMethodResponse'
        '500':
          description: 服务器内部错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'





components:
  schemas:
    User:
      properties:
        user_name:
          type: string
          description: 用户名，长度小于等于50
          example: "Plato"
        password:
          type: string
          description: 用户密码（前端加密后），加密后长度小于等于50
          example: "123456"
    FUserFullMsg:
      properties:
        user_name:
          type: string
          description: 用户名，长度小于等于50
          example: "Plato"
        password:
          type: string
          description: 用户密码（前端加密后），加密后长度小于等于50
          example: "123456"
        user_email:
          type: string
          format: email
          description: 用户邮箱，长度小于等于100
          example: "Plato@163.com"
    BUserFullMsg:
      properties:
        user_name:
          type: string
          description: 用户名，长度小于等于50
          example: "Plato"
        password:
          type: string
          description: 用户密码（前端加密后），加密后长度小于等于50
          example: "123456"
        user_email:
          type: string
          format: email
          description: 用户邮箱，长度小于等于100
          example: "Plato@163.com"
        avatar_url:
          type: string
          format: url
          description: 用户头像的url，前端需要使用get方法获取
          example: "188.228.11.2/avatars/plato.png"
    JWTResponse:
      required:
        - code
        - info
        - token
        - user_name
        - password
      properties:
        code:
          type: integer
          description: 0
          example: 0
        info:
          type: string
          description: Success
          default: "Success"
          example: "Success"
        token:
          type: string
          description: 服务端签发的JWT令牌
          example: "***.***.***"
        user_name:
          type: string
          description: 用户名，长度小于等于50
          example: "Plato"
        password:
          type: string
          description: 用户密码（前端加密后），加密后长度小于等于50
          example: "123456"
        user_email:
          type: string
          format: email
          description: 用户邮箱，长度小于等于100
          example: "Plato@163.com"
        avatar:
          type: string
          format: binary
          description: 用户头像的二进制文件
          example: "{FILE_BINARY}"
    SuccessResponse:
      type: object
      properties:
        code:
          type: integer
          description: 0
          example: 0
        info:
          type: string
          description: Success
          default: "Success"
          example: "Success"
    NotFoundResponse:
      type: object
      properties:
        code:
          type: integer
          description: -1
          example: -1
        info:
          type: string
          description: some message
          example: "some message"
    UnauthorizedResponse:
      type: object
      properties:
        code:
          type: integer
          description: -2
          example: -2
        info:
          type: string
          description: some message
          example: "some message"
    BadMethodResponse:
      type: object
      properties:
        code:
          type: integer
          description: -3
          example: -3
        info:
          type: string
          description: Bad method
          default: "Bad method"
          example: "Bad method"
    ServerErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: -4
          example: -4
        info:
          type: string
          description: Server error
          default: "Server error"
          example: "Server error"
    ConflictResponse:
      type: object
      properties:
        code:
          type: integer
          description: -5
          example: -5
        info:
          type: string
          description: some message
          example: "some message"

